const PDFDocument = require('pdfkit');

const generatePDF = (report, user) => {
  return new Promise((resolve, reject) => {
    const doc    = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data',  chunk => chunks.push(chunk));
    doc.on('end',   ()    => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.rect(0, 0, 595, 80).fill('#2b6cb0');
    doc.fontSize(22).fillColor('#ffffff')
       .text('Pneumonia Detection Report', 50, 25, { align: 'center', width: 495 });

    // Patient Info
    doc.fontSize(13).fillColor('#2d3748').text('Patient Information', 50, 100);
    doc.moveTo(50, 118).lineTo(545, 118).lineWidth(1).stroke('#cbd5e0');
    doc.fontSize(11).fillColor('#4a5568');
    doc.text(`Patient Name  :  ${user.name}`,  50, 128);
    doc.text(`Email         :  ${user.email}`, 50, 148);
    doc.text(`Report ID     :  ${report._id}`, 50, 168);
    doc.text(`Date          :  ${new Date(report.createdAt).toLocaleString()}`, 50, 188);

    // Result Box
    const isPneumonia = report.prediction === 'PNEUMONIA';
    const color       = isPneumonia ? '#e53e3e' : '#38a169';
    const bgColor     = isPneumonia ? '#fff5f5' : '#f0fff4';

    doc.rect(50, 220, 495, 110).fill(bgColor).stroke(color);
    doc.fontSize(20).fillColor(color)
       .text(isPneumonia ? 'PNEUMONIA DETECTED' : 'NORMAL', 50, 240, { align: 'center', width: 495 });
    doc.fontSize(12).fillColor('#2d3748')
       .text(`Confidence Score   :  ${(report.confidence * 100).toFixed(1)}%`, 50, 272, { align: 'center', width: 495 });
    doc.text(`Decision Threshold :  ${report.threshold}`, 50, 292, { align: 'center', width: 495 });

    // Confidence Bar
    doc.fontSize(11).fillColor('#4a5568').text('Confidence Level', 50, 350);
    doc.rect(50, 368, 495, 14).fill('#e2e8f0');
    doc.rect(50, 368, 495 * report.confidence, 14).fill(color);
    doc.fontSize(10).fillColor('#718096')
       .text(`${(report.confidence * 100).toFixed(1)}%`, 50, 386, { align: 'right', width: 495 });

    // Advice
    doc.fontSize(11).fillColor('#2d3748').text('Clinical Advice', 50, 415);
    doc.moveTo(50, 430).lineTo(545, 430).lineWidth(1).stroke('#cbd5e0');
    const advice = isPneumonia
      ? 'The AI model has detected signs consistent with pneumonia. Please consult a qualified medical professional immediately.'
      : 'No signs of pneumonia detected. The chest appears normal. Continue regular health check-ups.';
    doc.fontSize(11).fillColor('#4a5568').text(advice, 50, 440, { width: 495, lineGap: 4 });

    // Model Info
    doc.fontSize(11).fillColor('#2d3748').text('Model Information', 50, 510);
    doc.moveTo(50, 526).lineTo(545, 526).lineWidth(1).stroke('#cbd5e0');
    doc.fontSize(10).fillColor('#718096');
    doc.text('Algorithm  :  Random Forest Classifier',              50, 536);
    doc.text('Features   :  HOG (Histogram of Oriented Gradients)', 50, 552);
    doc.text('Image Size :  128x128 pixels (grayscale)',            50, 568);
    doc.text('Accuracy   :  88.8%  |  Macro F1: 0.88  |  ROC-AUC: 0.927', 50, 584);

    // Disclaimer
    doc.rect(0, 730, 595, 112).fill('#f7fafc');
    doc.fontSize(9).fillColor('#a0aec0')
       .text(
         'DISCLAIMER: This report is generated by an AI-based system and does not constitute a medical diagnosis. ' +
         'Always consult a licensed physician for proper medical advice and treatment.',
         50, 750, { width: 495, align: 'center', lineGap: 3 }
       );

    doc.end();
  });
};

module.exports = { generatePDF };